### ISSUE TITLE
Python 3 webserver not working on Windows 10

### ISSUE THREAD

**Issue by Hans-Zamorano-Matamala** [HimbeersaftLP/ios-safari-remote-debug-kit#2] opened 2022-04-17 22:06 UTC
Hi, when trying to run start.ps1 and then opening the suggested URL Chrome indicates that the website is not online, this also happen when trying to open localhost:8080. After modifying start.ps1 to not look for Python (line 46) it works perfectly by using the NodeJS one.

Environment: Windows 10 with Python 3 and NodeJS v17.2.0
Used for: iPhone 7 with iOS 15.4

Hope this info is useful.

**Comment by HimbeersaftLP** [comment] 2022-04-23 23:16
Hi, thanks for reporting this. I cannot reproduce this on my machine. Can you try removing the "| Out-Null" from this line and seeing if any error appears?
https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/blob/9e1a0e86779f308aab8d40ba14c2a161faf70cfe/src/start.ps1#L48

**Comment by Hans-Zamorano-Matamala** [comment] 2022-05-04 13:04
Hi, thanks for your reply. If I remove the line it throws an error specfying that python3.exe was not found. Effectively I can run python with "python" from command line, but not by using "python3", but if I type "python --version" it shows "Python 3.10" which is the version I have.

After installing python from Windows Store (which opened after typing python3.exe in powershell) everything worked.

**Comment by HimbeersaftLP** [comment] 2022-05-04 20:17
Ah, I'm guessing the issue is that even if python is not installed, windows aliases python.exe to the microsoft store link. I'll see if I can find a workaround.

**Comment by neil-hucker-seequent** [comment] 2023-09-28 20:47
I had this issue and got it working. To do this I had to:
Got to Windows 11: Settings > Apps > Advanced app settings > App execution aliases to turn off the aliases for both python.exe and python3.exe.
The start.ps1 script uses Get-Command "python3.exe" so once the aliases run this command and see where it points to.

For me, I use a python.exe on my environment path instead of a python3.exe. I updated the start.ps1 to just use python.exe instead of python3.exe ie:

    if (Get-Command "python.exe" -ErrorAction SilentlyContinue) {
        echo "Found Python, using it to serve the WebInspector"
        python.exe -m http.server $PORT --bind $SRV_HOST --directory $DIR 2>&1 | Out-Null

It's worth checking your firewall with httpserver by just running a basic web server in any directory and making sure it runs using the python on your environment path.
e.g. python.exe -m http.server -b localhost 8080
then navigate to localhost:8080 in webbrowser
if you have a firewall issue it will trigger it

since i've got other stuff running in docker on 8080 I changed it to 8081 and updated the $PORT in my host accordingly.
Also some systems for whatever reason need 127.0.0.1 instead of localhost (probably check your windows host file), so you may need to change $SRV_HOST = "localhost" to $SRV_HOST = "127.0.0.1" in you start.ps1.

If running according the instructions and you still see nothing, it's worth checking the page list by going to 
http://localhost:9222/
The site I was testing had a service worker on page 1 which wasn't returning anything and the page I needed was page 2
so I had to update
http://localhost:8081/Main.html?ws=127.0.0.1:9222/devtools/page/1
to
http://localhost:8081/Main.html?ws=127.0.0.1:9222/devtools/page/2

**Comment by HimbeersaftLP** [comment] 2023-10-01 10:53
I wish I could just bundle a small webserver executable so you don't need any dependencies, but all the ones I found trigger various antivirus tools

**Comment by HimbeersaftLP** [comment] 2023-10-04 20:47
@Hans-Zamorano-Matamala @JWess @neil-hucker-seequent Fixed in 77620eb0e1bbbb12590a071bcc4bf9ce02916e27
Could one of you tell me if this fix works for you?

**Comment by HimbeersaftLP** [comment] 2024-01-18 09:36
Since there have been no comments I will assume this is fixed now. Feel free to reopen

**Closed by HimbeersaftLP** 2024-01-18 09:36 UTC
